lesson1
glebeckaya/webix-jet-start pull request #1
Opened 2021-04-16 00:39 UTC by glebeckaya

2021-04-16 08:25 UTC, olimed commented on sources/views/data.js
> +								return false;
удаляй лишние  return

2021-04-16 08:25 UTC, olimed commented on sources/views/data.js
> +						editor: "text",
поля в таблице не редактируются

2021-04-16 08:30 UTC, glebeckaya commented on sources/views/data.js
> +						editor: "text",
исправила

2021-04-16 08:30 UTC, glebeckaya commented on sources/views/data.js
> +								return false;
удалила return

2021-04-16 08:31 UTC, olimed commented on sources/views/data.js
> +						editor: "text",
смотри коммент выше

2021-04-16 08:31 UTC, olimed commented on sources/views/data.js
> +				countries.add(Object({"Name": result}));
зачем ты объект преобразовываешь в объект?

2021-04-16 08:31 UTC, olimed commented on sources/views/data.js
> +				status["icon"] = statuses.getItem(idRandomStatus)["Icon"];
сейчас это не обязательно было делать, так как эти иконки пока не используются

2021-04-16 08:49 UTC, glebeckaya commented on sources/views/data.js
> +				countries.add(Object({"Name": result}));
да, лишняя обертка, убрала

2021-04-16 08:49 UTC, glebeckaya commented on sources/views/data.js
> +						editor: "text",
исправила

2021-04-16 12:04 UTC, Zwillinge requested changes

2021-04-16 12:04 UTC, Zwillinge commented on sources/views/data.js
> +			header: "Countries",
в этом модуле у нас лежит только (!) multiview, а яего ячейки вставлен один и тот же класс, описанный отдельно. можно передать несколько параметров в конструктор, если считаешь нужным  

```
new DataEditView(this.app, "", countries),
new DataEditView(this.app, "", statuses),
```

внутри этог класса есть общий для обеих ячеек конфиг и методы для работы с таблицей 
```
class DataEditView(){
    config
    init () //парсим данные из конструктора
    addItem() //добавляем элемент в таблицу
    removeItem() //удаляем
}
```

так мы используем один и тот же модуль для 2 ячеек мультивью, то есть учимся переиспользовать код внутри своего jetapp

2021-04-16 12:04 UTC, Zwillinge commented on sources/views/data.js
> +				status["icon"] = statuses.getItem(idRandomStatus)["Icon"];
и в будущем не придется. добавляем новую запить без иконки, но колонка editable. если челу нужна икнока, он пойдем и заполнит

2021-04-16 14:27 UTC, glebeckaya commented on sources/views/data.js
> +			header: "Countries",
добавила содержимое multiview c помощью отдельного класса

2021-04-16 14:28 UTC, glebeckaya commented on sources/views/data.js
> +				status["icon"] = statuses.getItem(idRandomStatus)["Icon"];
удалила эту часть

2021-04-16 19:48 UTC, Zwillinge commented on sources/views/data.js
> +			header: "Countries",
мне не очень понятно зачем были добавлены коллекции на этом этапе. да, они будут в след. ветке, но новые фичи мы делаем именно в новой ветке.  надо понимать, что здесь они не нужны. просто в методах addItem, removeItem мы данные обновляем именно в таблице, то есть в this.$$("datatable")

2021-04-16 20:38 UTC, glebeckaya commented on sources/views/data.js
> +			header: "Countries",
удалила

2021-04-16 20:47 UTC, Zwillinge commented on sources/views/data.js
> +			header: "Countries",
И небольшая мелочь: т. к. мы обращаемся к таблице несколько раз в модуле, имеет смысл её сохранить на $init как this.table = this.$$("datatable") и обращаться к this.table в других методах

2021-04-16 21:21 UTC, glebeckaya commented on sources/views/data.js
> +			header: "Countries",
сохранила как this.table

2021-04-17 07:26 UTC, Zwillinge approved these changes

2021-04-18 07:10 UTC, olimed approved these changes

2021-04-18 07:10 UTC, merged